apiVersion: v1
kind: Namespace
metadata:
  name: pro
  labels:
    name: pro
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: pro
spec:
  limits:
  - max:
      memory: 1Gi
    min:
      memory: 500Mi
    type: Container
