apiVersion: v1
kind: Secret
metadata:
  name: mysecret-string
type: Opaque
stringData:
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env:
      - name: USER
        valueFrom:
          secretKeyRef:
            name: mysecret-string
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret-string
            key: password